from faker_setup import fake

# creating a reference for countries, currencies, and teams

# ISO 3166-1 Country Reference List
# Format: (CountryID [Alpha-2], CodeAlphaThree, NumericCode, DisplayName)
COUNTRIES = [
    ("AF", "AFG", 4, "Afghanistan"),
    ("AX", "ALA", 248, "Åland Islands"),
    ("AL", "ALB", 8, "Albania"),
    ("DZ", "DZA", 12, "Algeria"),
    ("AS", "ASM", 16, "American Samoa"),
    ("AD", "AND", 20, "Andorra"),
    ("AO", "AGO", 24, "Angola"),
    ("AI", "AIA", 660, "Anguilla"),
    ("AQ", "ATA", 10, "Antarctica"),
    ("AG", "ATG", 28, "Antigua and Barbuda"),
    ("AR", "ARG", 32, "Argentina"),
    ("AM", "ARM", 51, "Armenia"),
    ("AW", "ABW", 533, "Aruba"),
    ("AU", "AUS", 36, "Australia"),
    ("AT", "AUT", 40, "Austria"),
    ("AZ", "AZE", 31, "Azerbaijan"),
    ("BS", "BHS", 44, "Bahamas"),
    ("BH", "BHR", 48, "Bahrain"),
    ("BD", "BGD", 50, "Bangladesh"),
    ("BB", "BRB", 52, "Barbados"),
    ("BY", "BLR", 112, "Belarus"),
    ("BE", "BEL", 56, "Belgium"),
    ("BZ", "BLZ", 84, "Belize"),
    ("BJ", "BEN", 204, "Benin"),
    ("BM", "BMU", 60, "Bermuda"),
    ("BT", "BTN", 64, "Bhutan"),
    ("BO", "BOL", 68, "Bolivia"),
    ("BQ", "BES", 535, "Bonaire, Sint Eustatius and Saba"),
    ("BA", "BIH", 70, "Bosnia and Herzegovina"),
    ("BW", "BWA", 72, "Botswana"),
    ("BV", "BVT", 74, "Bouvet Island"),
    ("BR", "BRA", 76, "Brazil"),
    ("IO", "IOT", 86, "British Indian Ocean Territory"),
    ("BN", "BRN", 96, "Brunei Darussalam"),
    ("BG", "BGR", 100, "Bulgaria"),
    ("BF", "BFA", 854, "Burkina Faso"),
    ("BI", "BDI", 108, "Burundi"),
    ("CV", "CPV", 132, "Cabo Verde"),
    ("KH", "KHM", 116, "Cambodia"),
    ("CM", "CMR", 120, "Cameroon"),
    ("CA", "CAN", 124, "Canada"),
    ("KY", "CYM", 136, "Cayman Islands"),
    ("CF", "CAF", 140, "Central African Republic"),
    ("TD", "TCD", 148, "Chad"),
    ("CL", "CHL", 152, "Chile"),
    ("CN", "CHN", 156, "China"),
    ("CX", "CXR", 162, "Christmas Island"),
    ("CC", "CCK", 166, "Cocos (Keeling) Islands"),
    ("CO", "COL", 170, "Colombia"),
    ("KM", "COM", 174, "Comoros"),
    ("CG", "COG", 178, "Congo"),
    ("CD", "COD", 180, "Congo, Democratic Republic of the"),
    ("CK", "COK", 184, "Cook Islands"),
    ("CR", "CRI", 188, "Costa Rica"),
    ("CI", "CIV", 384, "Côte d'Ivoire"),
    ("HR", "HRV", 191, "Croatia"),
    ("CU", "CUB", 192, "Cuba"),
    ("CW", "CUW", 531, "Curaçao"),
    ("CY", "CYP", 196, "Cyprus"),
    ("CZ", "CZE", 203, "Czechia"),
    ("DK", "DNK", 208, "Denmark"),
    ("DJ", "DJI", 262, "Djibouti"),
    ("DM", "DMA", 212, "Dominica"),
    ("DO", "DOM", 214, "Dominican Republic"),
    ("EC", "ECU", 218, "Ecuador"),
    ("EG", "EGY", 818, "Egypt"),
    ("SV", "SLV", 222, "El Salvador"),
    ("GQ", "GNQ", 226, "Equatorial Guinea"),
    ("ER", "ERI", 232, "Eritrea"),
    ("EE", "EST", 233, "Estonia"),
    ("SZ", "SWZ", 748, "Eswatini"),
    ("ET", "ETH", 231, "Ethiopia"),
    ("FK", "FLK", 238, "Falkland Islands"),
    ("FO", "FRO", 234, "Faroe Islands"),
    ("FJ", "FJI", 242, "Fiji"),
    ("FI", "FIN", 246, "Finland"),
    ("FR", "FRA", 250, "France"),
    ("GF", "GUF", 254, "French Guiana"),
    ("PF", "PYF", 258, "French Polynesia"),
    ("TF", "ATF", 260, "French Southern Territories"),
    ("GA", "GAB", 266, "Gabon"),
    ("GM", "GMB", 270, "Gambia"),
    ("GE", "GEO", 268, "Georgia"),
    ("DE", "DEU", 276, "Germany"),
    ("GH", "GHA", 288, "Ghana"),
    ("GI", "GIB", 292, "Gibraltar"),
    ("GR", "GRC", 300, "Greece"),
    ("GL", "GRL", 304, "Greenland"),
    ("GD", "GRD", 308, "Grenada"),
    ("GP", "GLP", 312, "Guadeloupe"),
    ("GU", "GUM", 316, "Guam"),
    ("GT", "GTM", 320, "Guatemala"),
    ("GG", "GGY", 831, "Guernsey"),
    ("GN", "GIN", 324, "Guinea"),
    ("GW", "GNB", 624, "Guinea-Bissau"),
    ("GY", "GUY", 328, "Guyana"),
    ("HT", "HTI", 332, "Haiti"),
    ("HM", "HMD", 334, "Heard Island and McDonald Islands"),
    ("VA", "VAT", 336, "Holy See"),
    ("HN", "HND", 340, "Honduras"),
    ("HK", "HKG", 344, "Hong Kong"),
    ("HU", "HUN", 348, "Hungary"),
    ("IS", "ISL", 352, "Iceland"),
    ("IN", "IND", 356, "India"),
    ("ID", "IDN", 360, "Indonesia"),
    ("IR", "IRN", 364, "Iran"),
    ("IQ", "IRQ", 368, "Iraq"),
    ("IE", "IRL", 372, "Ireland"),
    ("IM", "IMN", 833, "Isle of Man"),
    ("IL", "ISR", 376, "Israel"),
    ("IT", "ITA", 380, "Italy"),
    ("JM", "JAM", 388, "Jamaica"),
    ("JP", "JPN", 392, "Japan"),
    ("JE", "JEY", 832, "Jersey"),
    ("JO", "JOR", 400, "Jordan"),
    ("KZ", "KAZ", 398, "Kazakhstan"),
    ("KE", "KEN", 404, "Kenya"),
    ("KI", "KIR", 296, "Kiribati"),
    ("KP", "PRK", 408, "Korea (Democratic People's Republic of)"),
    ("KR", "KOR", 410, "Korea, Republic of"),
    ("KW", "KWT", 414, "Kuwait"),
    ("KG", "KGZ", 417, "Kyrgyzstan"),
    ("LA", "LAO", 418, "Lao People's Democratic Republic"),
    ("LV", "LVA", 428, "Latvia"),
    ("LB", "LBN", 422, "Lebanon"),
    ("LS", "LSO", 426, "Lesotho"),
    ("LR", "LBR", 430, "Liberia"),
    ("LY", "LBY", 434, "Libya"),
    ("LI", "LIE", 438, "Liechtenstein"),
    ("LT", "LTU", 440, "Lithuania"),
    ("LU", "LUX", 442, "Luxembourg"),
    ("MO", "MAC", 446, "Macao"),
    ("MG", "MDG", 450, "Madagascar"),
    ("MW", "MWI", 454, "Malawi"),
    ("MY", "MYS", 458, "Malaysia"),
    ("MV", "MDV", 462, "Maldives"),
    ("ML", "MLI", 466, "Mali"),
    ("MT", "MLT", 470, "Malta"),
    ("MH", "MHL", 584, "Marshall Islands"),
    ("MQ", "MTQ", 474, "Martinique"),
    ("MR", "MRT", 478, "Mauritania"),
    ("MU", "MUS", 480, "Mauritius"),
    ("YT", "MYT", 175, "Mayotte"),
    ("MX", "MEX", 484, "Mexico"),
    ("FM", "FSM", 583, "Micronesia (Federated States of)"),
    ("MD", "MDA", 498, "Moldova"),
    ("MC", "MCO", 492, "Monaco"),
    ("MN", "MNG", 496, "Mongolia"),
    ("ME", "MNE", 499, "Montenegro"),
    ("MS", "MSR", 500, "Montserrat"),
    ("MA", "MAR", 504, "Morocco"),
    ("MZ", "MOZ", 508, "Mozambique"),
    ("MM", "MMR", 104, "Myanmar"),
    ("NA", "NAM", 516, "Namibia"),
    ("NR", "NRU", 520, "Nauru"),
    ("NP", "NPL", 524, "Nepal"),
    ("NL", "NLD", 528, "Netherlands"),
    ("NC", "NCL", 540, "New Caledonia"),
    ("NZ", "NZL", 554, "New Zealand"),
    ("NI", "NIC", 558, "Nicaragua"),
    ("NE", "NER", 562, "Niger"),
    ("NG", "NGA", 566, "Nigeria"),
    ("NU", "NIU", 570, "Niue"),
    ("NF", "NFK", 574, "Norfolk Island"),
    ("MK", "MKD", 807, "North Macedonia"),
    ("MP", "MNP", 580, "Northern Mariana Islands"),
    ("NO", "NOR", 578, "Norway"),
    ("OM", "OMN", 512, "Oman"),
    ("PK", "PAK", 586, "Pakistan"),
    ("PW", "PLW", 585, "Palau"),
    ("PS", "PSE", 275, "Palestine, State of"),
    ("PA", "PAN", 591, "Panama"),
    ("PG", "PNG", 598, "Papua New Guinea"),
    ("PY", "PRY", 600, "Paraguay"),
    ("PE", "PER", 604, "Peru"),
    ("PH", "PHL", 608, "Philippines"),
    ("PN", "PCN", 612, "Pitcairn"),
    ("PL", "POL", 616, "Poland"),
    ("PT", "PRT", 620, "Portugal"),
    ("PR", "PRI", 630, "Puerto Rico"),
    ("QA", "QAT", 634, "Qatar"),
    ("RE", "REU", 638, "Réunion"),
    ("RO", "ROU", 642, "Romania"),
    ("RU", "RUS", 643, "Russian Federation"),
    ("RW", "RWA", 646, "Rwanda"),
    ("BL", "BLM", 652, "Saint Barthélemy"),
    ("SH", "SHN", 654, "Saint Helena, Ascension and Tristan da Cunha"),
    ("KN", "KNA", 659, "Saint Kitts and Nevis"),
    ("LC", "LCA", 662, "Saint Lucia"),
    ("MF", "MAF", 663, "Saint Martin (French part)"),
    ("PM", "SPM", 666, "Saint Pierre and Miquelon"),
    ("VC", "VCT", 670, "Saint Vincent and the Grenadines"),
    ("WS", "WSM", 882, "Samoa"),
    ("SM", "SMR", 674, "San Marino"),
    ("ST", "STP", 678, "Sao Tome and Principe"),
    ("SA", "SAU", 682, "Saudi Arabia"),
    ("SN", "SEN", 686, "Senegal"),
    ("RS", "SRB", 688, "Serbia"),
    ("SC", "SYC", 690, "Seychelles"),
    ("SL", "SLE", 694, "Sierra Leone"),
    ("SG", "SGP", 702, "Singapore"),
    ("SX", "SXM", 534, "Sint Maarten (Dutch part)"),
    ("SK", "SVK", 703, "Slovakia"),
    ("SI", "SVN", 705, "Slovenia"),
    ("SB", "SLB", 90, "Solomon Islands"),
    ("SO", "SOM", 706, "Somalia"),
    ("ZA", "ZAF", 710, "South Africa"),
    ("GS", "SGS", 239, "South Georgia and the South Sandwich Islands"),
    ("SS", "SSD", 728, "South Sudan"),
    ("ES", "ESP", 724, "Spain"),
    ("LK", "LKA", 144, "Sri Lanka"),
    ("SD", "SDN", 729, "Sudan"),
    ("SR", "SUR", 740, "Suriname"),
    ("SJ", "SJM", 744, "Svalbard and Jan Mayen"),
    ("SE", "SWE", 752, "Sweden"),
    ("CH", "CHE", 756, "Switzerland"),
    ("SY", "SYR", 760, "Syrian Arab Republic"),
    ("TW", "TWN", 158, "Taiwan"),
    ("TJ", "TJK", 762, "Tajikistan"),
    ("TZ", "TZA", 834, "Tanzania, United Republic of"),
    ("TH", "THA", 764, "Thailand"),
    ("TL", "TLS", 626, "Timor-Leste"),
    ("TG", "TGO", 768, "Togo"),
    ("TK", "TKL", 772, "Tokelau"),
    ("TO", "TON", 776, "Tonga"),
    ("TT", "TTO", 780, "Trinidad and Tobago"),
    ("TN", "TUN", 788, "Tunisia"),
    ("TR", "TUR", 792, "Türkiye"),
    ("TM", "TKM", 795, "Turkmenistan"),
    ("TC", "TCA", 796, "Turks and Caicos Islands"),
    ("TV", "TUV", 798, "Tuvalu"),
    ("UG", "UGA", 800, "Uganda"),
    ("UA", "UKR", 804, "Ukraine"),
    ("AE", "ARE", 784, "United Arab Emirates"),
    ("GB", "GBR", 826, "United Kingdom"),
    ("US", "USA", 840, "United States"),
    ("UM", "UMI", 581, "United States Minor Outlying Islands"),
    ("UY", "URY", 858, "Uruguay"),
    ("UZ", "UZB", 860, "Uzbekistan"),
    ("VU", "VUT", 548, "Vanuatu"),
    ("VE", "VEN", 862, "Venezuela"),
    ("VN", "VNM", 704, "Viet Nam"),
    ("VG", "VGB", 92, "Virgin Islands (British)"),
    ("VI", "VIR", 850, "Virgin Islands (U.S.)"),
    ("WF", "WLF", 876, "Wallis and Futuna"),
    ("EH", "ESH", 732, "Western Sahara"),
    ("YE", "YEM", 887, "Yemen"),
    ("ZM", "ZMB", 894, "Zambia"),
    ("ZW", "ZWE", 716, "Zimbabwe"),
]

# Currency Reference List: ISO 4217 Fiat + Major Cryptocurrencies
# Format: (CurrencyID [Alpha-3], CurrencyCode [Numeric], Name, CurrencyType, DecimalPlaces)
CURRENCIES = [
    ("AED", 784, "UAE Dirham", "FIAT", 2),
    ("AFN", 971, "Afghan Afghani", "FIAT", 2),
    ("ALL", 8, "Albanian Lek", "FIAT", 2),
    ("AMD", 51, "Armenian Dram", "FIAT", 2),
    ("ANG", 532, "Netherlands Antillean Guilder", "FIAT", 2),
    ("AOA", 973, "Angolan Kwanza", "FIAT", 2),
    ("ARS", 32, "Argentine Peso", "FIAT", 2),
    ("AUD", 36, "Australian Dollar", "FIAT", 2),
    ("AWG", 533, "Aruban Florin", "FIAT", 2),
    ("AZN", 944, "Azerbaijani Manat", "FIAT", 2),
    ("BAM", 977, "Bosnia and Herzegovina Convertible Mark", "FIAT", 2),
    ("BBD", 52, "Barbados Dollar", "FIAT", 2),
    ("BDT", 50, "Bangladeshi Taka", "FIAT", 2),
    ("BGN", 975, "Bulgarian Lev", "FIAT", 2),
    ("BHD", 48, "Bahraini Dinar", "FIAT", 3),
    ("BIF", 108, "Burundian Franc", "FIAT", 0),
    ("BMD", 60, "Bermudian Dollar", "FIAT", 2),
    ("BND", 96, "Brunei Dollar", "FIAT", 2),
    ("BOB", 68, "Boliviano", "FIAT", 2),
    ("BRL", 76, "Brazilian Real", "FIAT", 2),
    ("BSD", 44, "Bahamian Dollar", "FIAT", 2),
    ("BTN", 64, "Bhutanese Ngultrum", "FIAT", 2),
    ("BWP", 72, "Botswana Pula", "FIAT", 2),
    ("BYN", 933, "Belarusian Ruble", "FIAT", 2),
    ("BZD", 84, "Belize Dollar", "FIAT", 2),
    ("CAD", 124, "Canadian Dollar", "FIAT", 2),
    ("CDF", 976, "Congolese Franc", "FIAT", 2),
    ("CHF", 756, "Swiss Franc", "FIAT", 2),
    ("CLP", 152, "Chilean Peso", "FIAT", 0),
    ("CNY", 156, "Chinese Yuan", "FIAT", 2),
    ("COP", 170, "Colombian Peso", "FIAT", 2),
    ("CRC", 188, "Costa Rican Colon", "FIAT", 2),
    ("CUP", 192, "Cuban Peso", "FIAT", 2),
    ("CVE", 132, "Cabo Verde Escudo", "FIAT", 2),
    ("CZK", 203, "Czech Koruna", "FIAT", 2),
    ("DJF", 262, "Djiboutian Franc", "FIAT", 0),
    ("DKK", 208, "Danish Krone", "FIAT", 2),
    ("DOP", 214, "Dominican Peso", "FIAT", 2),
    ("DZD", 12, "Algerian Dinar", "FIAT", 2),
    ("EGP", 818, "Egyptian Pound", "FIAT", 2),
    ("ERN", 232, "Eritrean Nakfa", "FIAT", 2),
    ("ETB", 231, "Ethiopian Birr", "FIAT", 2),
    ("EUR", 978, "Euro", "FIAT", 2),
    ("FJD", 242, "Fiji Dollar", "FIAT", 2),
    ("FKP", 238, "Falkland Islands Pound", "FIAT", 2),
    ("GBP", 826, "Pound Sterling", "FIAT", 2),
    ("GEL", 981, "Georgian Lari", "FIAT", 2),
    ("GHS", 936, "Ghanaian Cedi", "FIAT", 2),
    ("GIP", 292, "Gibraltar Pound", "FIAT", 2),
    ("GMD", 270, "Gambian Dalasi", "FIAT", 2),
    ("GNF", 324, "Guinean Franc", "FIAT", 0),
    ("GTQ", 320, "Guatemalan Quetzal", "FIAT", 2),
    ("GYD", 328, "Guyana Dollar", "FIAT", 2),
    ("HKD", 344, "Hong Kong Dollar", "FIAT", 2),
    ("HNL", 340, "Honduran Lempira", "FIAT", 2),
    ("HTG", 332, "Haitian Gourde", "FIAT", 2),
    ("HUF", 348, "Hungarian Forint", "FIAT", 2),
    ("IDR", 360, "Indonesian Rupiah", "FIAT", 2),
    ("ILS", 376, "Israeli New Shekel", "FIAT", 2),
    ("INR", 356, "Indian Rupee", "FIAT", 2),
    ("IQD", 368, "Iraqi Dinar", "FIAT", 3),
    ("IRR", 364, "Iranian Rial", "FIAT", 2),
    ("ISK", 352, "Icelandic Krona", "FIAT", 0),
    ("JMD", 388, "Jamaican Dollar", "FIAT", 2),
    ("JOD", 400, "Jordanian Dinar", "FIAT", 3),
    ("JPY", 392, "Japanese Yen", "FIAT", 0),
    ("KES", 404, "Kenyan Shilling", "FIAT", 2),
    ("KGS", 417, "Kyrgyzstani Som", "FIAT", 2),
    ("KHR", 116, "Cambodian Riel", "FIAT", 2),
    ("KMF", 174, "Comorian Franc", "FIAT", 0),
    ("KPW", 408, "North Korean Won", "FIAT", 2),
    ("KRW", 410, "South Korean Won", "FIAT", 0),
    ("KWD", 414, "Kuwaiti Dinar", "FIAT", 3),
    ("KYD", 136, "Cayman Islands Dollar", "FIAT", 2),
    ("KZT", 398, "Kazakhstani Tenge", "FIAT", 2),
    ("LAK", 418, "Lao Kip", "FIAT", 2),
    ("LBP", 422, "Lebanese Pound", "FIAT", 2),
    ("LKR", 144, "Sri Lankan Rupee", "FIAT", 2),
    ("LRD", 430, "Liberian Dollar", "FIAT", 2),
    ("LSL", 426, "Lesotho Loti", "FIAT", 2),
    ("LYD", 434, "Libyan Dinar", "FIAT", 3),
    ("MAD", 504, "Moroccan Dirham", "FIAT", 2),
    ("MDL", 498, "Moldovan Leu", "FIAT", 2),
    ("MGA", 969, "Malagasy Ariary", "FIAT", 2),
    ("MKD", 807, "Macedonian Denar", "FIAT", 2),
    ("MMK", 104, "Myanmar Kyat", "FIAT", 2),
    ("MNT", 496, "Mongolian Tugrik", "FIAT", 2),
    ("MOP", 446, "Macanese Pataca", "FIAT", 2),
    ("MRU", 929, "Mauritanian Ouguiya", "FIAT", 2),
    ("MUR", 480, "Mauritian Rupee", "FIAT", 2),
    ("MVR", 462, "Maldivian Rufiyaa", "FIAT", 2),
    ("MWK", 454, "Malawian Kwacha", "FIAT", 2),
    ("MXN", 484, "Mexican Peso", "FIAT", 2),
    ("MYR", 458, "Malaysian Ringgit", "FIAT", 2),
    ("MZN", 943, "Mozambican Metical", "FIAT", 2),
    ("NAD", 516, "Namibian Dollar", "FIAT", 2),
    ("NGN", 566, "Nigerian Naira", "FIAT", 2),
    ("NIO", 558, "Nicaraguan Cordoba", "FIAT", 2),
    ("NOK", 578, "Norwegian Krone", "FIAT", 2),
    ("NPR", 524, "Nepalese Rupee", "FIAT", 2),
    ("NZD", 554, "New Zealand Dollar", "FIAT", 2),
    ("OMR", 512, "Omani Rial", "FIAT", 3),
    ("PAB", 590, "Panamanian Balboa", "FIAT", 2),
    ("PEN", 604, "Peruvian Sol", "FIAT", 2),
    ("PGK", 598, "Papua New Guinean Kina", "FIAT", 2),
    ("PHP", 608, "Philippine Peso", "FIAT", 2),
    ("PKR", 586, "Pakistani Rupee", "FIAT", 2),
    ("PLN", 985, "Polish Zloty", "FIAT", 2),
    ("PYG", 600, "Paraguayan Guarani", "FIAT", 0),
    ("QAR", 634, "Qatari Riyal", "FIAT", 2),
    ("RON", 946, "Romanian Leu", "FIAT", 2),
    ("RSD", 941, "Serbian Dinar", "FIAT", 2),
    ("RUB", 643, "Russian Ruble", "FIAT", 2),
    ("RWF", 646, "Rwandan Franc", "FIAT", 0),
    ("SAR", 682, "Saudi Riyal", "FIAT", 2),
    ("SBD", 90, "Solomon Islands Dollar", "FIAT", 2),
    ("SCR", 690, "Seychellois Rupee", "FIAT", 2),
    ("SDG", 938, "Sudanese Pound", "FIAT", 2),
    ("SEK", 752, "Swedish Krona", "FIAT", 2),
    ("SGD", 702, "Singapore Dollar", "FIAT", 2),
    ("SHP", 654, "Saint Helena Pound", "FIAT", 2),
    ("SLE", 925, "Sierra Leonean Leone", "FIAT", 2),
    ("SOS", 706, "Somali Shilling", "FIAT", 2),
    ("SRD", 968, "Surinamese Dollar", "FIAT", 2),
    ("SSP", 728, "South Sudanese Pound", "FIAT", 2),
    ("STN", 930, "Sao Tome and Principe Dobra", "FIAT", 2),
    ("SVC", 222, "El Salvador Colon", "FIAT", 2),
    ("SYP", 760, "Syrian Pound", "FIAT", 2),
    ("SZL", 748, "Swazi Lilangeni", "FIAT", 2),
    ("THB", 764, "Thai Baht", "FIAT", 2),
    ("TJS", 972, "Tajikistani Somoni", "FIAT", 2),
    ("TMT", 934, "Turkmenistan Manat", "FIAT", 2),
    ("TND", 788, "Tunisian Dinar", "FIAT", 3),
    ("TOP", 776, "Tongan Paʻanga", "FIAT", 2),
    ("TRY", 949, "Turkish Lira", "FIAT", 2),
    ("TTD", 780, "Trinidad and Tobago Dollar", "FIAT", 2),
    ("TWD", 901, "New Taiwan Dollar", "FIAT", 2),
    ("TZS", 834, "Tanzanian Shilling", "FIAT", 2),
    ("UAH", 980, "Ukrainian Hryvnia", "FIAT", 2),
    ("UGX", 800, "Ugandan Shilling", "FIAT", 0),
    ("USD", 840, "US Dollar", "FIAT", 2),
    ("UYU", 858, "Uruguayan Peso", "FIAT", 2),
    ("UZS", 860, "Uzbekistani Som", "FIAT", 2),
    ("VES", 928, "Venezuelan Bolivar Soberano", "FIAT", 2),
    ("VND", 704, "Vietnamese Dong", "FIAT", 0),
    ("VUV", 548, "Vanuatu Vatu", "FIAT", 0),
    ("WST", 882, "Samoan Tala", "FIAT", 2),
    ("XAF", 950, "CFA Franc BEAC", "FIAT", 0),
    ("XCD", 951, "East Caribbean Dollar", "FIAT", 2),
    ("XOF", 952, "CFA Franc BCEAO", "FIAT", 0),
    ("XPF", 953, "CFP Franc", "FIAT", 0),
    ("YER", 886, "Yemeni Rial", "FIAT", 2),
    ("ZAR", 710, "South African Rand", "FIAT", 2),
    ("ZMW", 967, "Zambian Kwacha", "FIAT", 2),
    ("ZWL", 932, "Zimbabwean Dollar", "FIAT", 2),
    # CRYPTOCURRENCIES & STABLECOINS
    ("BTC", 1001, "Bitcoin", "CRYPTO", 8),
    ("ETH", 1002, "Ethereum", "CRYPTO", 8),
    ("USDT", 1003, "Tether USD", "CRYPTO", 2),
    ("USDC", 1004, "USD Coin", "CRYPTO", 2),
    ("BNB", 1005, "BNB", "CRYPTO", 8),
    ("XRP", 1006, "XRP", "CRYPTO", 6),
    ("SOL", 1007, "Solana", "CRYPTO", 8),
    ("ADA", 1008, "Cardano", "CRYPTO", 6),
    ("DOGE", 1009, "Dogecoin", "CRYPTO", 8),
    ("TRX", 1010, "TRON", "CRYPTO", 6),
    ("AVAX", 1011, "Avalanche", "CRYPTO", 8),
    ("DOT", 1012, "Polkadot", "CRYPTO", 8),
    ("LINK", 1013, "Chainlink", "CRYPTO", 8),
    ("LTC", 1014, "Litecoin", "CRYPTO", 8),
    ("BCH", 1015, "Bitcoin Cash", "CRYPTO", 8),
    ("XLM", 1016, "Stellar Lumens", "CRYPTO", 7),
    ("NEAR", 1017, "NEAR Protocol", "CRYPTO", 8),
    ("UNI", 1018, "Uniswap", "CRYPTO", 8),
    ("DAI", 1019, "Dai Stablecoin", "CRYPTO", 2),
    ("TON", 1020, "Toncoin", "CRYPTO", 8),
    # Privacy Coins (AML High-Risk Focus)
    ("XMR", 1021, "Monero", "CRYPTO", 8),
    ("ZEC", 1022, "Zcash", "CRYPTO", 8),
]

TEAMS = [
    "AML",
    "Financial Crime",
    "Fraud",
    "Compliance",
]

ACTIVE = ["Y", "Y", "Y", "N"]


# generate countries
def generate_countries(connection):
    connection.executemany(
        """
        INSERT INTO Countries (CountryID, CodeAlphaThree, NumericCode, DisplayName)
        VALUES (?, ?, ?, ?)
        """,
        COUNTRIES,
    )
    return [country[0] for country in COUNTRIES]


# generate currencies
def generate_currencies(connection):
    connection.executemany(
        """
        INSERT INTO Currency (CurrencyID, CurrencyCode, Name, CurrencyType, DecimalPlaces)
        VALUES (?, ?, ?, ?, ?)
        """,
        CURRENCIES,
    )
    return [currency[0] for currency in CURRENCIES]


# generate analysts
def generate_analysts(connection, count):
    analyst_ids = []
    records = []

    for analyst_id in range(1, count + 1):
        name = fake.name()
        email = fake.unique.email()
        team = fake.random_element(TEAMS)
        active = fake.random_element(ACTIVE)

        records.append((analyst_id, name, email, team, active))
        analyst_ids.append(analyst_id)

    connection.executemany(
        """
        INSERT INTO Analyst (AnalystID, Name, Email, Team, Active)
        VALUES (?, ?, ?, ?, ?)
        """,
        records,
    )

    return analyst_ids
