from pathlib import Path

# project directories
BASE_DIR = Path(__file__).resolve().parent.parent
DATABASE_PATH = BASE_DIR/ "database" / "aml.db"

# number of records to generate
COUNTRY_COUNT = 20
CURRENCY_COUNT = 10
ANALYST_COUNT = 20
PARTY_COUNT = 1000
CUSTOMER_COUNT = 750
ACCOUNT_COUNT = 1000
TRANSACTION_COUNT = 1000
SANCTION_COUNT = 200
ALERT_COUNT = 300
CASE_COUNT = 150
CASE_ACTIVITY_COUNT = 500
CASE_CUSTOMER_RELATIONSHIP_COUNT = 300
CASE_SANCTION_RELATIONSHIP_COUNT = 150
CASE_TRANSACTION_RELATIONSHIP_COUNT = 300

# faker configuration
FAKER_LOCALE = "en_GB"
RANDOM_SEED = 12345