from pathlib import Path

# project directories
BASE_DIR = Path(__file__).resolve().parent.parent
DATABASE_PATH = BASE_DIR / "database" / "aml.db"

# number of records to generate
# scale volumes
COUNTRY_COUNT = 20
CURRENCY_COUNT = 10
ANALYST_COUNT = 25

CUSTOMER_COUNT = 10000
EMPLOYER_COUNT = 500
MERCHANT_COUNT = 1000
CRYPTO_COUNT = 50
BANK_BRANCH_COUNT = 150
FOREIGN_PARTY_COUNT = 300

ACCOUNT_COUNT = 1000
SANCTION_COUNT = 100

TOTAL_TRANSACTION_COUNT = 100000
SUSPICIOUS_TRANSACTION_COUNT = 500
NORMAL_TRANSACTION_COUNT = TOTAL_TRANSACTION_COUNT - SUSPICIOUS_TRANSACTION_COUNT

ALERT_COUNT = 1200
CASE_COUNT = 400
CASE_ACTIVITY_COUNT = 1200

CASE_CUSTOMER_RELATIONSHIP_COUNT = 300
CASE_SANCTION_RELATIONSHIP_COUNT = 150
CASE_TRANSACTION_RELATIONSHIP_COUNT = 300

# ratio and archetype weights
# daily transactions
SHOPPING = 0.5
SALARY = 0.1
PEER_TO_PEER_TRANSFERS = 0.2
CASH_DEPOSITS = 0.1
INTERNATIONAL_PAYMENTS = 0.07
CRPTO_PAYMENTS = 0.03

# faker configuration
FAKER_LOCALE = "en_GB"
RANDOM_SEED = 12345
